import { useEffect, useState } from 'react';
import { ArrowLeft, ChevronDown, ChevronRight, Pencil, Plus, Save, Trash2 } from 'lucide-react';
import AdminLayout from '../layouts/AdminLayout';
import { cms } from '../services/cmsService';
import { Input, Textarea, Select, SeoFields, EditorIntro, emptySeo } from '../components/CmsUI';

const lessonTypes = ['THEORY','SLIDES','VIDEO','SQL','PYTHON','PYSPARK','QUIZ','ASSIGNMENT','PROJECT','LIVE','RESOURCE'];
const labTypes = ['SQL','COLAB_PYTHON','COLAB_PYSPARK','GITHUB_CODE','TEXT_CODE','INTERNAL_PYTHON','INTERNAL_PYSPARK'];
const contentTypes = ['SLIDES','VIDEO','NOTES','ARTICLE','PDF','EMBED'];

const blankLesson = () => ({ title:'', slug:'', description:'', lessonType:'THEORY', durationMinutes:30, isPreview:false, status:'published', driveEmbedUrl:'', content:[], labs:[], assignment:{title:'',instructions:'',submissionType:'TEXT',status:'published'} });
const blankModule = () => ({ module:'', description:'', topics:[], lessons:[] });
const blank = () => ({ title:'',slug:'',tagline:'',shortDescription:'',overview:'',thumbnail:'',banner:'',category:'',duration:'',level:'',mode:'Online Live Classes',language:'English',certificateAvailable:true,certificateTitle:'Certificate of Completion',featured:false,students:'',rating:'',projects:0,displayOrder:0,comingSoon:false,popular:false,enrollmentOpen:true,lastUpdated:'',version:'1.0',status:'draft',accessType:'free',price:0,currency:'INR',technologies:[],curriculum:[],seo:emptySeo() });

const normalizeLesson = (l={}) => ({ ...blankLesson(), ...l, content:Array.isArray(l.content)?l.content:[], labs:Array.isArray(l.labs)?l.labs:[], assignment:{...blankLesson().assignment,...(l.assignment||{})} });
const normalizeModule = (m={}) => ({ ...blankModule(), ...m, topics:Array.isArray(m.topics)?m.topics:[], lessons:(m.lessons||[]).map(normalizeLesson) });
const fromApi = (x) => ({ ...blank(), ...x, shortDescription:x.shortDescription||'', accessType:x.accessType||'free', price:Number(x.price||0), currency:x.currency||'INR', seo:x.seo||emptySeo(), curriculum:(x.curriculum||[]).map(normalizeModule), technologies:x.technologies||[] });

export default function CoursesCMS(){
  const [items,setItems]=useState([]); const [editing,setEditing]=useState(null); const [loading,setLoading]=useState(true); const [error,setError]=useState(''); const [openModule,setOpenModule]=useState(0);
  const load=()=>cms.courses.list().then(setItems).catch(e=>setError(e.message)).finally(()=>setLoading(false));
  useEffect(()=>{load();},[]);
  const edit=async id=>{setError('');try{setEditing(fromApi(await cms.courses.get(id)));setOpenModule(0);}catch(e){setError(e.message)}};
  const save=async e=>{e.preventDefault();setError('');try{if(editing.id) await cms.courses.update(editing.id,editing); else await cms.courses.create(editing);setEditing(null);setLoading(true);load();}catch(e){setError(e.message)}};
  const remove=async id=>{if(!confirm('Delete this course? Curriculum, lessons and SEO will also be deleted.'))return;try{await cms.courses.remove(id);load();}catch(e){setError(e.message)}};
  if(editing) return <CourseEditor editing={editing} setEditing={setEditing} save={save} error={error} openModule={openModule} setOpenModule={setOpenModule} />;
  return <AdminLayout><div className="max-w-7xl mx-auto space-y-7">
    <div className="flex flex-col md:flex-row md:items-end md:justify-between gap-5"><div><p className="text-cyan-400 text-sm font-semibold uppercase tracking-wider">LMS Course CMS</p><h1 className="text-4xl font-bold mt-2">Courses</h1><p className="mt-2 text-slate-400">Create Course → Modules → Lessons → Slides/Labs → Student Access.</p></div><button onClick={()=>setEditing(blank())} className="inline-flex items-center gap-2 rounded-xl bg-blue-600 px-5 py-3 font-semibold hover:bg-blue-500"><Plus size={18}/> New Course</button></div>
    {error&&<div className="p-4 rounded-xl bg-red-500/10 text-red-400 border border-red-500/30">{error}</div>}
    {loading?<p className="text-slate-400">Loading courses…</p>:<div className="grid gap-4">{items.map(c=><div key={c.id} className="rounded-2xl border border-slate-800 bg-slate-900 p-5"><div className="flex flex-col lg:flex-row lg:items-center lg:justify-between gap-4"><div><div className="flex items-center gap-2"><h2 className="text-xl font-bold">{c.title}</h2><span className="text-xs rounded-full bg-slate-800 px-3 py-1">{c.status}</span><span className="text-xs rounded-full bg-cyan-500/10 text-cyan-300 px-3 py-1">{c.access_type||c.accessType||'free'} {Number(c.price||0)>0?`• ${c.currency||'INR'} ${c.price}`:''}</span></div><p className="text-sm text-slate-400 mt-2">/{c.slug} · {c.category||'Course'} · {c.modules_count||0} modules</p></div><div className="flex gap-2"><button onClick={()=>edit(c.id)} className="inline-flex items-center gap-2 rounded-lg bg-slate-800 px-4 py-2 text-cyan-300"><Pencil size={16}/> Edit Curriculum</button><button onClick={()=>remove(c.id)} className="p-2 rounded-lg bg-red-500/10 text-red-400"><Trash2 size={17}/></button></div></div></div>)}</div>}
  </div></AdminLayout>;
}

function cleanLessonHtml(html='') {
  const parser = new DOMParser();
  const doc = parser.parseFromString(`<div id=\"root\">${html}</div>`, 'text/html');
  const root = doc.querySelector('#root');
  if (!root) return html;
  let lastHeading='';
  root.querySelectorAll('h1,h2,h3,h4,h5,h6').forEach(h=>{
    const text=(h.textContent||'').replace(/\s+/g,' ').trim().toLowerCase();
    if (!text || text===lastHeading) { h.remove(); return; }
    lastHeading=text;
  });
  return root.innerHTML.trim();
}

function CourseEditor({editing,setEditing,save,error,openModule,setOpenModule}){
  const set=(key,val)=>setEditing({...editing,[key]:val});
  const modules=editing.curriculum||[];
  const addModule=()=>{set('curriculum',[...modules,blankModule()]);setOpenModule(modules.length)};
  const updateModule=(i,val)=>{const a=[...modules];a[i]={...a[i],...val};set('curriculum',a)};
  const removeModule=i=>set('curriculum',modules.filter((_,x)=>x!==i));
  const addLesson=i=>{const a=[...modules];a[i]={...a[i],lessons:[...(a[i].lessons||[]),blankLesson()]};set('curriculum',a);setOpenModule(i)};
  const updateLesson=(i,j,val)=>{const a=[...modules];const lessons=[...(a[i].lessons||[])];lessons[j]={...lessons[j],...val};a[i]={...a[i],lessons};set('curriculum',a)};
  const removeLesson=(i,j)=>{const a=[...modules];a[i]={...a[i],lessons:a[i].lessons.filter((_,x)=>x!==j)};set('curriculum',a)};
  const addContent=(i,j)=>updateLesson(i,j,{content:[...(modules[i].lessons[j].content||[]),{contentType:'NOTES',title:'',contentUrl:'',contentHtml:''}]});
  const setDriveEmbed=(i,j,url)=>updateLesson(i,j,{driveEmbedUrl:url});
  const cleanContent=(i,j,k)=>{const c=modules[i].lessons[j].content[k];updateContent(i,j,k,{contentHtml:cleanLessonHtml(c.contentHtml||'')});};
  const setAssignment=(i,j,val)=>updateLesson(i,j,{assignment:{...(modules[i].lessons[j].assignment||blankLesson().assignment),...val}});
  const uploadAssignmentText=(i,j,file)=>{if(!file)return; if(!file.name.toLowerCase().endsWith('.txt')){alert('Only .txt assignment files are allowed.');return;} const reader=new FileReader(); reader.onload=()=>setAssignment(i,j,{instructions:String(reader.result||'')}); reader.readAsText(file);};
  const updateContent=(i,j,k,val)=>{const c=[...(modules[i].lessons[j].content||[])];c[k]={...c[k],...val};updateLesson(i,j,{content:c});};
  const removeContent=(i,j,k)=>updateLesson(i,j,{content:modules[i].lessons[j].content.filter((_,x)=>x!==k)});
  const addLab=(i,j)=>updateLesson(i,j,{labs:[...(modules[i].lessons[j].labs||[]),{labType:'SQL',title:'SQL Practice Lab',externalUrl:'',instructions:'',datasetUrl:'',config:null}]});
  const updateLab=(i,j,k,val)=>{const labs=[...(modules[i].lessons[j].labs||[])];labs[k]={...labs[k],...val};updateLesson(i,j,{labs});};
  const removeLab=(i,j,k)=>updateLesson(i,j,{labs:modules[i].lessons[j].labs.filter((_,x)=>x!==k)});
  return <AdminLayout><div className="max-w-7xl mx-auto space-y-6">
    <div className="flex items-center justify-between gap-4"><button onClick={()=>history.back()} type="button" className="flex items-center gap-2 text-slate-400 hover:text-white"><ArrowLeft size={18}/> Courses</button><button form="course-editor" className="inline-flex items-center gap-2 rounded-xl bg-blue-600 px-5 py-3 font-semibold hover:bg-blue-500"><Save size={18}/> Save Course</button></div>
    <div><p className="text-cyan-400 text-sm font-semibold uppercase tracking-wider">Course Builder</p><h1 className="text-4xl font-bold mt-2">{editing.id?'Edit Course':'Create Course'}</h1><p className="mt-2 text-slate-400">The database hierarchy is Course → Module → Lesson → Content/Lab.</p></div>
    {error&&<div className="p-4 rounded-xl bg-red-500/10 text-red-400 border border-red-500/30">{error}</div>}
    <form id="course-editor" onSubmit={save} className="space-y-6">
      <EditorIntro title="Course access rule">Anyone can create a student account. Free courses become available after enrollment. Paid courses require payment integration or admin enrollment. Invite courses are admin-controlled.</EditorIntro>
      <section className="rounded-2xl border border-slate-800 bg-slate-900 p-6"><h2 className="text-2xl font-bold">1. Course Details</h2><div className="grid md:grid-cols-2 gap-5 mt-5">
        <Input label="Course Title *" value={editing.title} required onChange={e=>set('title',e.target.value)}/><Input label="Slug *" value={editing.slug} required onChange={e=>set('slug',e.target.value)}/><Input label="Tagline" value={editing.tagline} onChange={e=>set('tagline',e.target.value)}/><Input label="Category" value={editing.category} onChange={e=>set('category',e.target.value)}/><Input label="Duration" value={editing.duration} onChange={e=>set('duration',e.target.value)}/><Input label="Level" value={editing.level} onChange={e=>set('level',e.target.value)}/><Input label="Language" value={editing.language} onChange={e=>set('language',e.target.value)}/><Input label="Mode" value={editing.mode} onChange={e=>set('mode',e.target.value)}/><Input label="Thumbnail URL" value={editing.thumbnail} onChange={e=>set('thumbnail',e.target.value)}/><Input label="Banner URL" value={editing.banner} onChange={e=>set('banner',e.target.value)}/><Select label="Status" value={editing.status} onChange={e=>set('status',e.target.value)}><option>draft</option><option>published</option><option>archived</option></Select><Input label="Display Order" type="number" value={editing.displayOrder} onChange={e=>set('displayOrder',Number(e.target.value))}/></div>
        <Textarea label="Short Description" rows={3} value={editing.shortDescription} onChange={e=>set('shortDescription',e.target.value)}/><Textarea label="Overview" rows={6} value={editing.overview} onChange={e=>set('overview',e.target.value)}/>
        <div className="grid md:grid-cols-3 gap-5"><Select label="Access Type" value={editing.accessType} onChange={e=>set('accessType',e.target.value)}><option value="free">Free</option><option value="paid">Paid</option><option value="invite">Invite Only</option></Select><Input label="Price" type="number" min="0" step="0.01" value={editing.price} onChange={e=>set('price',Number(e.target.value))}/><Input label="Currency" value={editing.currency} onChange={e=>set('currency',e.target.value.toUpperCase())}/></div>
        <div className="flex flex-wrap gap-5 mt-4 text-sm"><label><input type="checkbox" checked={!!editing.enrollmentOpen} onChange={e=>set('enrollmentOpen',e.target.checked)}/> <span className="ml-2">Enrollment Open</span></label><label><input type="checkbox" checked={!!editing.featured} onChange={e=>set('featured',e.target.checked)}/> <span className="ml-2">Featured</span></label><label><input type="checkbox" checked={!!editing.popular} onChange={e=>set('popular',e.target.checked)}/> <span className="ml-2">Popular</span></label><label><input type="checkbox" checked={!!editing.certificateAvailable} onChange={e=>set('certificateAvailable',e.target.checked)}/> <span className="ml-2">Certificate</span></label></div>
      </section>

      <section className="rounded-2xl border border-slate-800 bg-slate-900 p-6"><div className="flex flex-col md:flex-row md:items-center md:justify-between gap-3"><div><h2 className="text-2xl font-bold">2. Curriculum Builder</h2><p className="text-slate-400 mt-1">Create modules and real lessons. Old topic entries are retained for backward compatibility.</p></div><button type="button" onClick={addModule} className="inline-flex items-center gap-2 rounded-xl bg-blue-600 px-4 py-2"><Plus size={17}/> Add Module</button></div>
        <div className="mt-5 space-y-4">{modules.map((m,i)=><div key={i} className="rounded-2xl border border-slate-700 overflow-hidden"><button type="button" onClick={()=>setOpenModule(openModule===i?-1:i)} className="w-full flex items-center justify-between p-5 bg-slate-950/60 text-left"><span className="flex items-center gap-3"><span className="text-cyan-400 font-bold">{String(i+1).padStart(2,'0')}</span><span className="font-bold">{m.module||'Untitled Module'}</span><span className="text-xs text-slate-500">{(m.lessons||[]).length} lessons</span></span>{openModule===i?<ChevronDown/>:<ChevronRight/>}</button>{openModule===i&&<div className="p-5 space-y-5"><div className="flex gap-3"><Input label="Module Name *" value={m.module} onChange={e=>updateModule(i,{module:e.target.value})}/><button type="button" onClick={()=>removeModule(i)} className="mt-7 p-3 text-red-400"><Trash2/></button></div><Textarea label="Module Description" rows={2} value={m.description||''} onChange={e=>updateModule(i,{description:e.target.value})}/><div className="flex justify-between items-center"><h3 className="text-lg font-semibold">Lessons</h3><button type="button" onClick={()=>addLesson(i)} className="inline-flex items-center gap-2 rounded-lg bg-slate-800 px-3 py-2 text-cyan-300"><Plus size={16}/> Add Lesson</button></div>
          {(m.lessons||[]).map((l,j)=><LessonEditor key={j} lesson={l} index={j} onChange={v=>updateLesson(i,j,v)} onRemove={()=>removeLesson(i,j)} addContent={()=>addContent(i,j)} updateContent={(k,v)=>updateContent(i,j,k,v)} removeContent={k=>removeContent(i,j,k)} cleanContent={k=>cleanContent(i,j,k)} setDriveEmbed={url=>setDriveEmbed(i,j,url)} uploadAssignmentText={file=>uploadAssignmentText(i,j,file)} setAssignment={v=>setAssignment(i,j,v)} addLab={()=>addLab(i,j)} updateLab={(k,v)=>updateLab(i,j,k,v)} removeLab={k=>removeLab(i,j,k)}/>)}</div>}</div>)}</div>
      </section>

      <section className="rounded-2xl border border-slate-800 bg-slate-900 p-6"><h2 className="text-2xl font-bold">3. Technologies</h2><div className="mt-4 grid md:grid-cols-2 gap-3">{(editing.technologies||[]).map((t,i)=><div className="flex gap-2" key={i}><Input label={`Technology ${i+1}`} value={t} onChange={e=>{const a=[...editing.technologies];a[i]=e.target.value;set('technologies',a)}}/><button type="button" onClick={()=>set('technologies',editing.technologies.filter((_,x)=>x!==i))} className="mt-7 text-red-400"><Trash2/></button></div>)}</div><button type="button" onClick={()=>set('technologies',[...editing.technologies,''])} className="mt-4 rounded-lg bg-slate-800 px-4 py-2">+ Add Technology</button></section>
      <SeoFields value={editing.seo} onChange={seo=>set('seo',seo)}/>
      <div className="flex justify-end"><button className="inline-flex items-center gap-2 rounded-xl bg-blue-600 px-7 py-3 font-semibold"><Save size={18}/> Save Course</button></div>
    </form>
  </div></AdminLayout>;
}

function LessonEditor({lesson,index,onChange,onRemove,addContent,updateContent,removeContent,cleanContent,setDriveEmbed,uploadAssignmentText,setAssignment,addLab,updateLab,removeLab}){
  return <div className="rounded-xl border border-slate-700 bg-slate-950/50 p-4 space-y-4"><div className="flex items-center justify-between"><h4 className="font-semibold text-cyan-300">Lesson {index+1}</h4><button type="button" onClick={onRemove} className="text-red-400"><Trash2 size={17}/></button></div><div className="grid md:grid-cols-2 gap-4"><Input label="Lesson Title *" value={lesson.title} onChange={e=>onChange({title:e.target.value})}/><Input label="Slug" value={lesson.slug} onChange={e=>onChange({slug:e.target.value})}/><Select label="Lesson Type" value={lesson.lessonType} onChange={e=>onChange({lessonType:e.target.value})}>{lessonTypes.map(x=><option key={x}>{x}</option>)}</Select><Input label="Duration (minutes)" type="number" value={lesson.durationMinutes} onChange={e=>onChange({durationMinutes:Number(e.target.value)})}/><Select label="Status" value={lesson.status} onChange={e=>onChange({status:e.target.value})}><option>published</option><option>draft</option><option>archived</option></Select><label className="flex items-center gap-2 mt-8 text-sm"><input type="checkbox" checked={!!lesson.isPreview} onChange={e=>onChange({isPreview:e.target.checked})}/> Free preview lesson</label></div><Textarea label="Lesson Description" rows={2} value={lesson.description||''} onChange={e=>onChange({description:e.target.value})}/>
    <div className="border-t border-slate-800 pt-4"><div className="flex items-center justify-between"><div><h5 className="font-semibold">Lesson Content</h5><p className="text-xs text-slate-500">Keep only the actual learning content. Repeated lesson headings can be cleaned before saving.</p></div><button type="button" onClick={addContent} className="rounded-lg bg-slate-800 px-3 py-2 text-sm">+ Content</button></div><div className="mt-3 rounded-xl border border-cyan-500/20 bg-cyan-500/5 p-4"><div className="font-semibold text-cyan-200">Google Drive PPT / PDF Embed</div><p className="text-xs text-slate-500 mt-1">Paste a Google Drive file or Google Slides URL. Students will see it inside the lesson.</p><div className="mt-3 flex gap-2"><input value={lesson.driveEmbedUrl||''} onChange={e=>setDriveEmbed(e.target.value)} placeholder="https://drive.google.com/file/d/.../view" className="flex-1 rounded-xl bg-slate-800 border border-slate-700 px-4 py-3 text-white outline-none focus:border-cyan-500"/><button type="button" onClick={()=>setDriveEmbed('')} className="rounded-xl bg-slate-800 px-4 text-sm">Clear</button></div></div><div className="mt-3 space-y-3">{(lesson.content||[]).map((c,k)=><div key={k} className="rounded-xl border border-slate-800 p-3 space-y-3"><div className="grid md:grid-cols-[150px_1fr_1fr_auto] gap-2 items-end"><Select label="Type" value={c.contentType} onChange={e=>updateContent(k,{contentType:e.target.value})}>{contentTypes.map(x=><option key={x}>{x}</option>)}</Select><Input label="Title" value={c.title||''} onChange={e=>updateContent(k,{title:e.target.value})}/><Input label="URL" value={c.contentUrl||''} onChange={e=>updateContent(k,{contentUrl:e.target.value})}/><button type="button" onClick={()=>removeContent(k)} className="mb-2 text-red-400"><Trash2 size={17}/></button></div><Textarea label="HTML Content — only lesson content" rows={8} value={c.contentHtml||''} onChange={e=>updateContent(k,{contentHtml:e.target.value})}/><button type="button" onClick={()=>cleanContent(k)} className="rounded-lg bg-cyan-500/10 text-cyan-300 px-3 py-2 text-xs">Clean repeated headings</button></div>)}</div></div>
    <div className="border-t border-slate-800 pt-4"><div className="flex items-center justify-between"><div><h5 className="font-semibold">Assignment</h5><p className="text-xs text-slate-500">Upload a plain-text assignment file. Its contents become the student assignment instructions.</p></div></div><div className="mt-3 rounded-xl border border-purple-500/20 bg-purple-500/5 p-4 space-y-3"><div className="grid md:grid-cols-2 gap-3"><Input label="Assignment Title" value={lesson.assignment?.title||''} onChange={e=>setAssignment({title:e.target.value})}/><Select label="Status" value={lesson.assignment?.status||'published'} onChange={e=>setAssignment({status:e.target.value})}><option value="published">published</option><option value="draft">draft</option></Select></div><input type="file" accept=".txt,text/plain" onChange={e=>uploadAssignmentText(e.target.files?.[0])} className="block w-full text-sm text-slate-300 file:mr-4 file:rounded-lg file:border-0 file:bg-purple-600 file:px-4 file:py-2 file:text-white"/><Textarea label="Assignment Text" rows={8} value={lesson.assignment?.instructions||''} onChange={e=>setAssignment({instructions:e.target.value})}/></div></div>
    <div className="border-t border-slate-800 pt-4"><div className="flex items-center justify-between"><div><h5 className="font-semibold">Lab</h5><p className="text-xs text-slate-500">SQL is internal. Python/PySpark can initially use Colab links.</p></div><button type="button" onClick={addLab} className="rounded-lg bg-slate-800 px-3 py-2 text-sm">+ Lab</button></div><div className="mt-3 space-y-4">{(lesson.labs||[]).map((lab,k)=><div key={k} className="rounded-xl border border-slate-800 p-4"><div className="grid md:grid-cols-2 gap-3"><Select label="Lab Type" value={lab.labType} onChange={e=>updateLab(k,{labType:e.target.value})}>{labTypes.map(x=><option key={x}>{x}</option>)}</Select><Input label="Lab Title" value={lab.title} onChange={e=>updateLab(k,{title:e.target.value})}/><Input label="External URL / Colab URL" value={lab.externalUrl||''} onChange={e=>updateLab(k,{externalUrl:e.target.value})}/><Input label="GitHub Path (repo/file/folder URL)" value={lab.config?.githubPath||''} onChange={e=>updateLab(k,{config:{...(lab.config||{}),githubPath:e.target.value}})}/><Input label="Dataset URL" value={lab.datasetUrl||''} onChange={e=>updateLab(k,{datasetUrl:e.target.value})}/></div><Textarea label="Instructions" rows={2} value={lab.instructions||''} onChange={e=>updateLab(k,{instructions:e.target.value})}/>{['TEXT_CODE','GITHUB_CODE'].includes(lab.labType)&&<Textarea label="Starter / Editable Code" rows={8} value={lab.config?.codeText||''} onChange={e=>updateLab(k,{config:{...(lab.config||{}),codeText:e.target.value}})}/>}<button type="button" onClick={()=>removeLab(k)} className="text-xs text-red-400">Remove lab</button></div>)}</div></div>
  </div>;
}
