import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { Plus, Pencil, Trash2, ArrowLeft } from 'lucide-react';
import AdminLayout from '../layouts/AdminLayout';
import { cms } from '../services/cmsService';
import { Input, Textarea, Select, SeoFields, emptySeo } from '../components/CmsUI';

const blank = () => ({ title:'',slug:'',tagline:'',shortDescription:'',overview:'',thumbnail:'',banner:'',category:'',duration:'',level:'',mode:'Online Live Classes',language:'English',certificateAvailable:true,certificateTitle:'Certificate of Completion',featured:false,students:'',rating:'',projects:0,displayOrder:0,comingSoon:false,popular:false,enrollmentOpen:true,lastUpdated:'',version:'1.0',status:'draft',technologies:[],curriculum:[],seo:emptySeo() });
const fromApi = (x) => ({ ...blank(), ...x, shortDescription:x.shortDescription||'', certificateAvailable:x.certificate_available ?? x.certificateAvailable ?? true, seo:x.seo||emptySeo(), curriculum:(x.curriculum||[]).map(m=>({module:m.module||'',description:m.description||'',topics:m.topics||[]})), technologies:x.technologies||[] });

export default function CoursesCMS(){
  const [items,setItems]=useState([]),[editing,setEditing]=useState(null),[loading,setLoading]=useState(true),[error,setError]=useState('');
  const load=()=>cms.courses.list().then(setItems).catch(e=>setError(e.message)).finally(()=>setLoading(false));
  useEffect(()=>{load()},[]);
  const edit=async id=>{setError('');try{setEditing(fromApi(await cms.courses.get(id)))}catch(e){setError(e.message)}};
  const save=async e=>{e.preventDefault();setError('');try{if(editing.id) await cms.courses.update(editing.id,editing); else await cms.courses.create(editing);setEditing(null);setLoading(true);load()}catch(e){setError(e.message)}};
  const remove=async id=>{if(!confirm('Delete this course? This also deletes curriculum and SEO.'))return;try{await cms.courses.remove(id);load()}catch(e){setError(e.message)}};
  if(editing)return <AdminLayout><div className="max-w-6xl space-y-6"><Link to="/admin/courses" onClick={()=>setEditing(null)} className="text-slate-400 flex gap-2 items-center"><ArrowLeft size={18}/> Courses</Link><div><h1 className="text-4xl font-bold">{editing.id?'Edit Course':'New Course'}</h1><p className="text-slate-400 mt-2">Course content, curriculum and SEO are saved in MySQL.</p></div>{error&&<div className="p-4 rounded-xl bg-red-500/10 text-red-400 border border-red-500/30">{error}</div>}
  <form onSubmit={save} className="space-y-6">
   <div className="grid md:grid-cols-2 gap-5"><Input label="Course Title *" value={editing.title} required onChange={e=>setEditing({...editing,title:e.target.value})}/><Input label="Slug *" value={editing.slug} required onChange={e=>setEditing({...editing,slug:e.target.value})}/><Input label="Tagline" value={editing.tagline} onChange={e=>setEditing({...editing,tagline:e.target.value})}/><Input label="Category" value={editing.category} onChange={e=>setEditing({...editing,category:e.target.value})}/><Input label="Duration" value={editing.duration} onChange={e=>setEditing({...editing,duration:e.target.value})}/><Input label="Level" value={editing.level} onChange={e=>setEditing({...editing,level:e.target.value})}/><Input label="Language" value={editing.language} onChange={e=>setEditing({...editing,language:e.target.value})}/><Input label="Mode" value={editing.mode} onChange={e=>setEditing({...editing,mode:e.target.value})}/><Input label="Students" value={editing.students} onChange={e=>setEditing({...editing,students:e.target.value})}/><Input label="Rating" type="number" step="0.1" value={editing.rating} onChange={e=>setEditing({...editing,rating:e.target.value})}/><Input label="Projects" type="number" value={editing.projects} onChange={e=>setEditing({...editing,projects:e.target.value})}/><Input label="Display Order" type="number" value={editing.displayOrder} onChange={e=>setEditing({...editing,displayOrder:e.target.value})}/><Input label="Thumbnail URL" value={editing.thumbnail} onChange={e=>setEditing({...editing,thumbnail:e.target.value})}/><Input label="Banner URL" value={editing.banner} onChange={e=>setEditing({...editing,banner:e.target.value})}/><Input label="Icon" value={editing.icon||''} onChange={e=>setEditing({...editing,icon:e.target.value})}/><Input label="Theme Color" value={editing.themeColor||''} onChange={e=>setEditing({...editing,themeColor:e.target.value})}/><Input label="Version" value={editing.version} onChange={e=>setEditing({...editing,version:e.target.value})}/><Input label="Last Updated" type="date" value={editing.lastUpdated||''} onChange={e=>setEditing({...editing,lastUpdated:e.target.value})}/><Select label="Status" value={editing.status} onChange={e=>setEditing({...editing,status:e.target.value})}><option>draft</option><option>published</option><option>archived</option></Select></div>
   <Textarea label="Short Description" rows={3} value={editing.shortDescription} onChange={e=>setEditing({...editing,shortDescription:e.target.value})}/><Textarea label="Overview" rows={7} value={editing.overview} onChange={e=>setEditing({...editing,overview:e.target.value})}/>
   <div className="grid md:grid-cols-4 gap-4 text-sm"><label><input type="checkbox" checked={!!editing.featured} onChange={e=>setEditing({...editing,featured:e.target.checked})}/> <span className="ml-2">Featured</span></label><label><input type="checkbox" checked={!!editing.popular} onChange={e=>setEditing({...editing,popular:e.target.checked})}/> <span className="ml-2">Popular</span></label><label><input type="checkbox" checked={!!editing.enrollmentOpen} onChange={e=>setEditing({...editing,enrollmentOpen:e.target.checked})}/> <span className="ml-2">Enrollment Open</span></label><label><input type="checkbox" checked={!!editing.comingSoon} onChange={e=>setEditing({...editing,comingSoon:e.target.checked})}/> <span className="ml-2">Coming Soon</span></label></div>
   <div className="rounded-2xl border border-slate-700 bg-slate-900/70 p-6"><h2 className="text-xl font-bold mb-4">Technologies</h2><div className="space-y-3">{editing.technologies.map((t,i)=><div className="flex gap-2" key={i}><Input label={`Technology ${i+1}`} value={t} onChange={e=>{const a=[...editing.technologies];a[i]=e.target.value;setEditing({...editing,technologies:a})}}/><button type="button" onClick={()=>setEditing({...editing,technologies:editing.technologies.filter((_,x)=>x!==i)})} className="mt-7 p-3 text-red-400"><Trash2/></button></div>)}</div><button type="button" onClick={()=>setEditing({...editing,technologies:[...editing.technologies,'']})} className="mt-4 px-4 py-2 rounded-lg bg-slate-800">+ Add Technology</button></div>
   <div className="rounded-2xl border border-slate-700 bg-slate-900/70 p-6"><div className="flex justify-between"><h2 className="text-xl font-bold">Curriculum</h2><button type="button" onClick={()=>setEditing({...editing,curriculum:[...editing.curriculum,{module:'',description:'',topics:[]} ]})} className="px-4 py-2 rounded-lg bg-blue-600">+ Add Module</button></div><div className="mt-5 space-y-5">{editing.curriculum.map((m,i)=><div key={i} className="border border-slate-700 rounded-xl p-5"><div className="flex gap-3"><Input label={`Module ${i+1}`} value={m.module} onChange={e=>{const a=[...editing.curriculum];a[i]={...a[i],module:e.target.value};setEditing({...editing,curriculum:a})}}/><button type="button" onClick={()=>setEditing({...editing,curriculum:editing.curriculum.filter((_,x)=>x!==i)})} className="mt-7 text-red-400"><Trash2/></button></div><Textarea label="Module Description" rows={2} value={m.description||''} onChange={e=>{const a=[...editing.curriculum];a[i]={...a[i],description:e.target.value};setEditing({...editing,curriculum:a})}}/><div className="mt-4 space-y-3">{(m.topics||[]).map((t,j)=><div className="flex gap-2" key={j}><Input label={`Topic ${j+1}`} value={t} onChange={e=>{const a=[...editing.curriculum];const topics=[...a[i].topics];topics[j]=e.target.value;a[i]={...a[i],topics};setEditing({...editing,curriculum:a})}}/><button type="button" onClick={()=>{const a=[...editing.curriculum];a[i]={...a[i],topics:a[i].topics.filter((_,x)=>x!==j)};setEditing({...editing,curriculum:a})}} className="mt-7 text-red-400"><Trash2/></button></div>)}</div><button type="button" onClick={()=>{const a=[...editing.curriculum];a[i]={...a[i],topics:[...(a[i].topics||[]),'']};setEditing({...editing,curriculum:a})}} className="mt-4 px-3 py-2 rounded-lg bg-slate-800">+ Add Topic</button></div>)}</div></div>
   <SeoFields value={editing.seo} onChange={seo=>setEditing({...editing,seo})}/>
   <div className="flex gap-3"><button className="px-7 py-3 rounded-xl bg-blue-600 font-semibold">Save Course</button><button type="button" onClick={()=>setEditing(null)} className="px-7 py-3 rounded-xl bg-slate-800">Cancel</button></div>
  </form></div></AdminLayout>;
  return <AdminLayout><div className="space-y-6"><div className="flex justify-between items-center"><div><h1 className="text-4xl font-bold">Courses</h1><p className="text-slate-400 mt-2">Create, edit, publish, archive and delete courses.</p></div><button onClick={()=>setEditing(blank())} className="px-5 py-3 rounded-xl bg-blue-600 flex gap-2 items-center"><Plus size={18}/> New Course</button></div>{error&&<div className="p-4 rounded-xl bg-red-500/10 text-red-400">{error}</div>}{loading?<p className="text-slate-400">Loading…</p>:<div className="overflow-auto rounded-2xl border border-slate-800"><table className="w-full text-left"><thead className="bg-slate-900 text-slate-400"><tr><th className="p-4">Course</th><th>Status</th><th>Slug</th><th className="p-4">Actions</th></tr></thead><tbody>{items.map(c=><tr key={c.id} className="border-t border-slate-800"><td className="p-4 font-semibold">{c.title}</td><td><span className="px-3 py-1 rounded-full bg-slate-800">{c.status}</span></td><td className="text-slate-400">/courses/{c.slug}</td><td className="p-4 flex gap-2"><button onClick={()=>edit(c.id)} className="p-2 rounded-lg bg-slate-800"><Pencil size={17}/></button><button onClick={()=>remove(c.id)} className="p-2 rounded-lg bg-red-500/10 text-red-400"><Trash2 size={17}/></button></td></tr>)}</tbody></table></div>}</div></AdminLayout>;
}
