import { useEffect, useState } from 'react';
import { CheckCircle2, ExternalLink } from 'lucide-react';
import { Link, useParams } from 'react-router-dom';
import { getLearningLesson, saveLessonProgress } from '../../services/lmsService';
import SqlLab from '../../components/student/SqlLab';
import LearningExperience from '../../components/student/LearningExperience';

export default function LearningLesson(){
 const {slug,lessonSlug}=useParams(); const [data,setData]=useState(null); const [error,setError]=useState(''); const [saving,setSaving]=useState(false);
 useEffect(()=>{getLearningLesson(slug,lessonSlug).then(setData).catch(e=>setError(e.message));},[slug,lessonSlug]);
 if(error) return <div className="min-h-screen bg-slate-950 text-white flex items-center justify-center"><div className="text-center"><h1 className="text-2xl font-bold">{error}</h1><Link to={`/learn/${slug}`} className="text-cyan-400 mt-4 inline-block">Back to course</Link></div></div>;
 if(!data) return <div className="min-h-screen bg-slate-950 text-white flex items-center justify-center">Loading lesson…</div>;
 const l=data.lesson; const progress=data.progress?.progress_percent||data.progress?.progressPercent||0;
 const complete=async()=>{setSaving(true);try{await saveLessonProgress(l.id,100);setData({...data,progress:{...(data.progress||{}),progress_percent:100,status:'COMPLETED'}});}finally{setSaving(false)}};
 return <div className="min-h-screen bg-[#030712] text-white"><header className="border-b border-slate-800 bg-slate-950/90 sticky top-0 z-40"><div className="max-w-5xl mx-auto px-5 py-4"><Link to={`/learn/${slug}`} className="text-slate-400 hover:text-white">← Back to course</Link></div></header><main className="max-w-5xl mx-auto px-5 py-8 pb-20"><div className="flex flex-wrap items-center gap-3 text-xs text-slate-500"><span className="rounded-full bg-cyan-500/10 text-cyan-300 px-3 py-1">{l.lessonType}</span>{l.durationMinutes>0&&<span>{l.durationMinutes} min</span>}</div><h1 className="text-4xl md:text-5xl font-bold mt-4">{l.title}</h1><p className="text-lg text-slate-400 mt-3 max-w-3xl">{l.description}</p><div className="mt-8 space-y-6">{l.driveEmbedUrl&&<DriveEmbed url={l.driveEmbedUrl}/>} {(l.content||[]).map((c,i)=><Content key={i} c={c}/>) }{(l.labs||[]).map(lab=>lab.labType==='SQL'?<SqlLab key={lab.id||lab.labType} lab={lab}/>:<Lab key={lab.id||lab.labType} lab={lab}/>)}{!(l.content?.length||l.labs?.length)&&<div className="rounded-2xl border border-dashed border-slate-700 p-8 text-slate-400">Lesson content is being prepared. You can still mark this lesson complete.</div>}</div><LearningExperience courseSlug={slug} lessonSlug={lessonSlug}/><div className="mt-10 rounded-2xl border border-slate-800 bg-slate-900 p-5"><div className="flex justify-between text-sm"><span className="text-slate-400">Lesson progress</span><span>{progress}%</span></div><div className="h-2 rounded-full bg-slate-800 mt-2"><div className="h-full bg-cyan-400 rounded-full" style={{width:`${progress}%`}}/></div><button disabled={saving||progress>=100} onClick={complete} className="mt-5 inline-flex items-center gap-2 rounded-xl bg-emerald-600 px-5 py-3 font-semibold disabled:opacity-50">{progress>=100?<><CheckCircle2 size={18}/> Completed</>:saving?'Saving…':<><CheckCircle2 size={18}/> Complete Lesson</>}</button></div></main></div>
}
function drivePreviewUrl(url='') {
 const u=String(url).trim();
 if(!u) return '';
 const file=u.match(/drive\.google\.com\/file\/d\/([^/]+)/i);
 if(file) return `https://drive.google.com/file/d/${file[1]}/preview`;
 const slides=u.match(/docs\.google\.com\/presentation\/d\/([^/]+)/i);
 if(slides) return `https://docs.google.com/presentation/d/${slides[1]}/embed`;
 return u;
}
function DriveEmbed({url}){const src=drivePreviewUrl(url); return <section className="rounded-2xl border border-cyan-500/20 bg-slate-900 overflow-hidden"><div className="px-5 py-4 border-b border-slate-800"><h2 className="font-bold">Course Material</h2><p className="text-xs text-slate-500 mt-1">PPT / PDF reference material</p></div><div className="p-2 bg-black"><iframe title="Course PPT or PDF" src={src} className="w-full min-h-[720px] border-0" loading="lazy" allow="autoplay"/></div></section>}
function Content({c}){return <section className="rounded-2xl border border-slate-800 bg-slate-900 overflow-hidden">{c.contentUrl?<><div className="px-5 py-3 border-b border-slate-800 text-sm font-semibold">Reference Material</div><div className="p-2 bg-black"><iframe title={c.title||c.contentType} src={c.contentUrl} className="w-full min-h-[650px] border-0" loading="lazy"/></div></>:c.contentHtml?<div className="p-6 prose prose-invert max-w-none" dangerouslySetInnerHTML={{__html:c.contentHtml}}/>:<div className="p-6 text-slate-500">No lesson content configured.</div>}</section>}
function Lab({lab}){const cfg=lab.config||{}; const external=lab.labType!=='SQL' && lab.externalUrl; const github=cfg.githubPath; const code=cfg.codeText; return <section className="rounded-2xl border border-cyan-500/20 bg-cyan-500/5 p-6"><div className="flex items-start justify-between gap-4"><div><p className="text-xs text-cyan-400 uppercase tracking-wider">Hands-on Lab</p><h2 className="text-2xl font-bold mt-1">{lab.title}</h2><p className="text-sm text-slate-400 mt-2">{lab.instructions||'Practice this concept hands-on.'}</p></div><span className="rounded-full bg-slate-900 px-3 py-1 text-xs">{lab.labType}</span></div>{lab.datasetUrl&&<a href={lab.datasetUrl} target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 mt-4 text-cyan-300 text-sm"><ExternalLink size={15}/> Dataset</a>}<div className="mt-5 flex flex-wrap gap-3">{external&&<a href={lab.externalUrl} target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 rounded-xl bg-blue-600 px-5 py-3 font-semibold"><ExternalLink size={17}/> Open in Colab</a>}{github&&<a href={github} target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 rounded-xl bg-slate-800 px-5 py-3 font-semibold text-cyan-300"><ExternalLink size={17}/> Open GitHub Code</a>}</div>{code&&<div className="mt-5"><div className="text-xs uppercase tracking-wider text-slate-500 mb-2">Starter / Editable Code</div><pre className="max-h-[520px] overflow-auto rounded-xl border border-slate-800 bg-[#020617] p-4 text-sm text-emerald-200 whitespace-pre-wrap"><code>{code}</code></pre></div>}{!external&&!github&&!code&&<div className="mt-5 rounded-xl bg-slate-950 border border-slate-800 p-5 text-slate-400"><strong className="text-white">{lab.labType==='INTERNAL_PYSPARK'?'Production PySpark Lab':'Hands-on Lab'}</strong><br/>{lab.instructions||'Use the starter material, implement the task and document your validation.'}</div>}</section>}
