import { useEffect, useState } from 'react';
import { BookOpen, CheckCircle2, Clock3, Code2, ExternalLink, GraduationCap, PlayCircle } from 'lucide-react';
import { Link } from 'react-router-dom';
import { useAuth } from '../../contexts/AuthContext';
import { getStudentDashboard } from '../../services/lmsService';

export default function StudentDashboard(){
  const { user } = useAuth(); const [data,setData]=useState(null); const [error,setError]=useState('');
  useEffect(()=>{getStudentDashboard().then(setData).catch(e=>setError(e.message));},[]);
  const courses=data?.courses||[]; const completed=courses.filter(c=>c.status==='COMPLETED').length;
  return <div className="min-h-screen bg-[#030712] text-white"><header className="border-b border-slate-800 bg-slate-950/90 sticky top-0 z-40"><div className="max-w-7xl mx-auto px-5 py-4 flex items-center justify-between"><Link to="/" className="font-bold text-xl">INFINITY <span className="text-cyan-400">AI CLOUD ACADEMY</span></Link><div className="text-sm text-slate-400">{user?.full_name || user?.email}</div></div></header>
    <main className="max-w-7xl mx-auto px-5 py-8 space-y-8"><section className="rounded-3xl border border-slate-800 bg-gradient-to-r from-blue-950/70 to-cyan-950/30 p-7"><div className="flex flex-col lg:flex-row lg:items-center lg:justify-between gap-6"><div><p className="text-cyan-400 font-semibold">STUDENT DASHBOARD</p><h1 className="text-4xl md:text-5xl font-bold mt-2">Welcome, {user?.full_name?.split(' ')[0] || 'Student'} 👋</h1><p className="mt-3 text-slate-300">Learn → Code → Run → Practice → Build → Get Industry Ready.</p></div><div className="rounded-2xl bg-white/5 border border-white/10 p-5 min-w-56"><p className="text-sm text-slate-400">Active Courses</p><p className="text-4xl font-bold mt-1">{courses.filter(c=>c.status==='ACTIVE').length}</p><p className="text-xs text-slate-500 mt-1">{completed} completed</p></div></div></section>
      {error&&<div className="rounded-xl bg-red-500/10 border border-red-500/20 p-4 text-red-300">{error}</div>}
      <section><div className="flex items-center justify-between mb-4"><div><h2 className="text-2xl font-bold">My Courses</h2><p className="text-slate-400 text-sm mt-1">Your enrolled learning programs.</p></div></div>{!data?<div className="text-slate-400">Loading courses…</div>:courses.length===0?<Empty/>:<div className="grid md:grid-cols-2 xl:grid-cols-3 gap-5">{courses.map(c=><CourseCard key={c.id} course={c}/>)}</div>}</section>
      <section className="grid md:grid-cols-3 gap-5"><Quick icon={<BookOpen/>} title="My Learning" text="Continue enrolled lessons." to="/student"/><Quick icon={<Code2/>} title="Practice Labs" text="SQL, Python and PySpark labs inside lessons." to="/courses"/><Quick icon={<GraduationCap/>} title="Certificates" text="Certificates will appear here after completion." to="/student"/></section>
    </main></div>
}
function CourseCard({course:c}){return <div className="rounded-2xl border border-slate-800 bg-slate-900 overflow-hidden"><div className="h-36 bg-gradient-to-br from-blue-900/80 to-cyan-900/30 flex items-end p-5"><div><span className="text-xs rounded-full bg-emerald-500/10 text-emerald-300 px-3 py-1">{c.status}</span><h3 className="text-xl font-bold mt-3">{c.title}</h3></div></div><div className="p-5"><div className="flex justify-between text-sm"><span className="text-slate-400">Progress</span><span className="font-semibold">{c.progressPercent}%</span></div><div className="mt-2 h-2 rounded-full bg-slate-800 overflow-hidden"><div className="h-full bg-gradient-to-r from-blue-500 to-cyan-400" style={{width:`${c.progressPercent}%`}}/></div><div className="mt-4 flex items-center gap-4 text-xs text-slate-500"><span className="flex items-center gap-1"><CheckCircle2 size={14}/> {c.completedLessons}/{c.totalLessons}</span><span className="flex items-center gap-1"><Clock3 size={14}/> {c.lastAccessedAt?'Recently active':'Not started'}</span></div><Link to={`/learn/${c.slug}`} className="mt-5 flex items-center justify-center gap-2 rounded-xl bg-blue-600 py-3 font-semibold hover:bg-blue-500"><PlayCircle size={17}/> Continue Learning</Link></div></div>}
function Quick({icon,title,text,to}){return <Link to={to} className="rounded-2xl border border-slate-800 bg-slate-900 p-5 hover:border-cyan-500/40"><div className="text-cyan-400">{icon}</div><h3 className="font-bold mt-4">{title}</h3><p className="text-sm text-slate-400 mt-1">{text}</p></Link>}
function Empty(){return <div className="rounded-2xl border border-dashed border-slate-700 p-10 text-center"><BookOpen className="mx-auto text-slate-500"/><h3 className="font-bold text-xl mt-4">No courses enrolled yet</h3><p className="text-slate-400 mt-2">Explore courses and enroll in a free course or purchase a paid program.</p><Link to="/courses" className="inline-block mt-5 rounded-xl bg-blue-600 px-5 py-3 font-semibold">Explore Courses</Link></div>}
